-- MySQL Script generated by MySQL Workbench
-- Fri Feb 24 18:18:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AnimalitosDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AnimalitosDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AnimalitosDB` DEFAULT CHARACTER SET utf8mb4 ;
USE `AnimalitosDB` ;

-- -----------------------------------------------------
-- Table `AnimalitosDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnimalitosDB`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `userImage` VARCHAR(45) NULL,
  `interes` VARCHAR(45) NULL,
  `user_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- Dumping data for table `Users`
--
INSERT INTO users (id, full_name, user_name, email, date_of_birth, password, userImage, interes, user_type) VALUES
(1,'Rodrigo Alsogaray', 'ralsogaray', 'ralsogaray@hotmail.com', '1991-10-24', '123456', '', 'cat', 'admin'),
(2,'Pato', 'Solari', 'patriciomsolari@gmail.com', '1989-06-17', '1234', '', 'dog', ''),
(3,'Vero', 'vero', 'vero@test.com', '1970-10-06', '123456', '', 'dog', 'admin');



-- -----------------------------------------------------
-- Table `AnimalitosDB`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnimalitosDB`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

--
-- Dumping data for table `Products`
--
INSERT INTO products (id, name, price, description, category, image) VALUES
(1, 'Owl, madagascar hawk', 13591, 'ridiculus mus vivamus', 'dogFood', 'alimento-excellent-gatos.png'),
(2, 'Dik Kirks', 1000, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 'dogFood', 'agility-perro-adulto.jpeg'),
(3, 'Dik Kirks', 9500, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 'dogFood', 'AlimentoAdulto.png'),
(4, 'Dik Kirks', 7000, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 'dogFood', 'AlimentoCachorro.png'),
(5, 'Woodcock, american', 1500, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 'catFood', 'AlimentoSenior.png'),
(6, 'Woodcock, american', 1500, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 'catFood', 'AlimentoSenior.png'),
(7, 'Woodcock, american', 1500, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 'catFood', 'AlimentoCachorro.png'),
(8, 'Woodcock, american', 1500, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 'catFood', 'AlimentoCachorro.png');



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
