-- MySQL Script generated by MySQL Workbench
-- Fri Feb 24 18:18:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AnimalitosDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AnimalitosDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AnimalitosDB` DEFAULT CHARACTER SET utf8mb4 ;
USE `AnimalitosDB` ;

-- -----------------------------------------------------
-- Table `AnimalitosDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnimalitosDB`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `userImage` VARCHAR(45) NULL,
  `interes` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnimalitosDB`.`product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnimalitosDB`.`product_categories` (
  `id_categorias` INT NOT NULL AUTO_INCREMENT,
  `cats` VARCHAR(45) NOT NULL,
  `dogs` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnimalitosDB`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnimalitosDB`.`products` (
  `id_products` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `id_category` INT NOT NULL,
  `image` VARCHAR(45) NULL
  PRIMARY KEY (`id_products`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnimalitosDB`.`sales_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnimalitosDB`.`sales_details` (
  `sales_detail_id` INT NOT NULL AUTO_INCREMENT,
  `id_products` INT NOT NULL,
  `id_sales` INT NULL,
  `amount` INT NULL,
  `price` DOUBLE NULL,
  `subTotal` DOUBLE NULL,
  `sales_id` VARCHAR(45) NULL,
  PRIMARY KEY (`sales_detail_id`),
  INDEX `fk_sales_details_products1_idx` (`id_products` ASC),
  CONSTRAINT `fk_sales_details_products1`
    FOREIGN KEY (`id_products`)
    REFERENCES `AnimalitosDB`.`products` (`id_products`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnimalitosDB`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnimalitosDB`.`sales` (
  `id_sales` INT NOT NULL AUTO_INCREMENT,
  `id_users` INT NOT NULL,
  `date` DATE NOT NULL,
  `sales_details_id` INT NOT NULL,
  PRIMARY KEY (`id_sales`),
  INDEX `fk_ventas_usuarios_idx` (`id_users` ASC),
  INDEX `fk_ventas_detalle_ventas1_idx` (`sales_details_id` ASC),
  CONSTRAINT `fk_ventas_usuarios`
    FOREIGN KEY (`id_users`)
    REFERENCES `AnimalitosDB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_detalle_ventas1`
    FOREIGN KEY (`sales_details_id`)
    REFERENCES `AnimalitosDB`.`sales_details` (`sales_detail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
