-- MySQL Script generated by MySQL Workbench
-- Fri Feb 24 18:18:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AnimalitosDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AnimalitosDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AnimalitosDB` DEFAULT CHARACTER SET utf8mb4 ;
USE `AnimalitosDB` ;

-- -----------------------------------------------------
-- Table `AnimalitosDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnimalitosDB`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `userImage` VARCHAR(45) NULL,
  `interes` VARCHAR(45) NULL,
  `user_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- Dumping data for table `Users`
--
INSERT INTO users (id, full_name, user_name, email, date_of_birth, password, userImage, interes, user_type) VALUES
(1,'Rodrigo Alsogaray', 'ralsogaray', 'ralsogaray@hotmail.com', '1991-10-24', '123456', '', 'cat', 'admin'),
(2,'Pato', 'Solari', 'patriciomsolari@gmail.com', '1989-06-17', '1234', '', 'dog', ''),
(3,'Vero', 'vero', 'vero@test.com', '1970-10-06', '123456', '', 'dog', 'admin');



-- -----------------------------------------------------
-- Table `AnimalitosDB`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnimalitosDB`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

--
-- Dumping data for table `Products`
--
INSERT INTO products (id, name, price, description, category, image) VALUES
(1, 'Excellent para gatos', 13981.18, 'Alimento para gatos con todos los nutrientes que tu mascota necesita', 'catFood', 'alimento-excellent-gatos.png'),
(2, 'Agility - Perros Adultos', 7970.64, 'Agility para perros es lo que tu mascota necesita!', 'dogFood', 'agility-perro-adulto.jpeg'),
(3, 'Purina Excellent', 9500, 'Exellent de Purina para perros es lo que tu mascota necesita!', 'dogFood', 'AlimentoAdulto.png'),
(4, 'Purina Excellent para Cachorros', 7000, 'Exellent de Purina para cachorros es lo que tu mascota necesita!', 'dogFood', 'AlimentoCachorro.png'),
(5, 'Purina Excellent Senior', 1500, 'Exellent de Purina para Seniors es lo que tu mascota necesita!', 'dogFood', 'AlimentoSenior.png'),
(6, 'Purina Excellent para gatos seniors', 1500, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 'catFood', 'alimento-excellent-gatos.png'),
(7, 'Purina Excellent para gatos castrados', 2500, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 'catFood', 'alimento-excellent-gatos.png'),
(8, 'Purina Excellent para gatos persas', 3500, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 'catFood', 'alimento-excellent-gatos.png');



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
